export const FETCH_ALL_CALENDARS_REQUEST = 'FETCH_ALL_CALENDARS_REQUEST';
export const FETCH_ALL_CALENDARS_SUCCESS = 'FETCH_ALL_CALENDARS_SUCCESS';
export const FETCH_ALL_CALENDARS_FAILURE = 'FETCH_ALL_CALENDARS_FAILURE';

export const FETCH_CAMPAIGN_MATRIX_REQUEST = 'FETCH_CAMPAIGN_MATRIX_REQUEST';
export const FETCH_CAMPAIGN_MATRIX_SUCCESS = 'FETCH_CAMPAIGN_MATRIX_SUCCESS';
export const FETCH_CAMPAIGN_MATRIX_FAILURE = 'FETCH_CAMPAIGN_MATRIX_FAILURE';

export const FETCH_DETAILED_TABLE_REQUEST = 'FETCH_DETAILED_TABLE_REQUEST';
export const FETCH_DETAILED_TABLE_SUCCESS = 'FETCH_DETAILED_TABLE_SUCCESS';
export const FETCH_DETAILED_TABLE_FAILURE = 'FETCH_DETAILED_TABLE_FAILURE';
