export const FETCH_ALL_CALENDARS_REQUEST = 'FETCH_ALL_CALENDARS_REQUEST';
export const FETCH_ALL_CALENDARS_SUCCESS = 'FETCH_ALL_CALENDARS_SUCCESS';
export const FETCH_ALL_CALENDARS_FAILURE = 'FETCH_ALL_CALENDARS_FAILURE';
